MiscGuild/bridge

index.js
=> make non color better

index.js
=> more colors

index.js
=> add mute logs

index.js
fixed some weird spacing in code and output
=> some random stuff

index.js
rank colors have priority over leave/join
I TESTED MY CODE FOR ONCE ELIJAH!
=> color change

index.js
@ElijahRus250 make sure to enable member intents and presence intents in dev portal
doesn't work for timing i'll do that later
if u let the mute run out of time the person will stay muted in the discord 4ever so u should probably not merge rn
=> mute syncing YAy

index.js
also some other code refactoring
=> /hub after 50 minutes and go back to limbo

index.js
cant test all of it right now i tested most of it before so if you gooonna piss your pants dont merge it
=> change chat

index.js
elijah is it your goal to make your code unreadable
like am i reading greek
=> make code better

index.js
lets pretend like there wasn't a bug there
=> fix timing

index.js
many things
extremely many things
=> rank things

index.js
sry for not in same pr im dumb at gh
=> make it more customizable pt 2

index.js
@Fury-101 @ElijahRus250 fixed i think
=> fixed guild join message

SlashCommands/blacklist.js, SlashCommands/command.js, SlashCommands/demote.js, SlashCommands/kick.js, SlashCommands/promote.js, SlashCommands/reboot.js
btw didnt test this so assume it works cause im leastrio
=> Lol ephemeral slash commands

index.js
https://github.com/PrismarineJS/mineflayer/issues/2328#issuecomment-985246695
=> fix(mineflayer): prevent ReDoS

resources/regex.js
update regex to avoid redos attacks
=> regex update

src/classes/Bot.ts, src/commands/help.ts, src/commands/reboot.ts, src/commands/uploadEmoji.ts, src/events/discord/interactionCreate.ts, src/events/discord/message.ts, src/events/discord/ready.ts, src/events/mineflayer/chat/commentBlocked.ts, src/events/mineflayer/chat/guildChat.ts, src/events/mineflayer/chat/guildMuteUnmute.ts, src/events/mineflayer/chat/joinLimbo.ts, src/events/mineflayer/chat/joinRequest.ts, src/events/mineflayer/chat/lobbyJoin.ts, src/events/mineflayer/chat/memberCount.ts, src/events/mineflayer/chat/memberJoinLeave.ts, src/events/mineflayer/chat/memberKick.ts, src/events/mineflayer/chat/whisper.ts, src/events/mineflayer/handler/end.ts, src/events/mineflayer/handler/error.ts, src/events/mineflayer/handler/login.ts, src/events/mineflayer/handler/message.ts, src/util/isUserBlacklisted.ts
- Remove unnecessary async functions
- Remove unnecessary `await`s
- Replace unnecessary sequential `await`s with `Promise.all()` (Not sure if this is good practice but I think so...)
Will test code soon to ensure full functionality.
=> Refactor asynchronous behaviour

package-lock.json, package.json
=> Revert "chore(deps): bump discord.js from 13.8.1 to 14.0.3"

.env.template, README.md, src/classes/Bot.ts
Increase executeTask error listener timeout
=> fix: catch more errors in executeTask

.gitignore, src/classes/bot.ts, src/events/mineflayer/chat/fetch-stats/bw-stats.ts, src/events/mineflayer/chat/fetch-stats/cvc/cvc-stats-defusal.ts, src/events/mineflayer/chat/fetch-stats/cvc/cvc-stats-overall.ts, src/events/mineflayer/chat/fetch-stats/cvc/cvc-stats-tdm.ts, src/events/mineflayer/chat/fetch-stats/duels/duels-stats-blitz.ts, src/events/mineflayer/chat/fetch-stats/duels/duels-stats-bridge.ts, src/events/mineflayer/chat/fetch-stats/duels/duels-stats-classic.ts, src/events/mineflayer/chat/fetch-stats/duels/duels-stats-combo.ts, src/events/mineflayer/chat/fetch-stats/duels/duels-stats-op.ts, src/events/mineflayer/chat/fetch-stats/duels/duels-stats-overall.ts, src/events/mineflayer/chat/fetch-stats/duels/duels-stats-sumo.ts, src/events/mineflayer/chat/fetch-stats/duels/duels-stats-sw.ts, src/events/mineflayer/chat/fetch-stats/duels/duels-stats-uhc.ts, src/events/mineflayer/chat/fetch-stats/mm-stats.ts, src/events/mineflayer/chat/fetch-stats/sw-stats.ts, src/events/mineflayer/chat/guild-mute-unmute.ts, src/events/mineflayer/chat/join-leave.ts, src/events/mineflayer/chat/member-join-leave.ts, src/events/mineflayer/chat/member-kick.ts, src/events/mineflayer/chat/whisper.ts, src/events/regex.ts, src/requests/fetch-hypixel-guild.ts, src/util/env.ts, src/util/log-error.ts
**Fix:** Several Issues regarding formatting & eslint
**Add:** reload all commands upon starting the bot using REST api
=> Several Issues Fixed
